From alpine:edge

# chromiumをインストール
RUN apk add --update \
        udev \
        ttf-freefont \
        chromium \
        chromium-chromedriver \
        curl

# 最新のchromedriverをインストール
#RUN CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` \
#  && curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip \
#  && unzip /tmp/chromedriver_linux64.zip \
#  && mv chromedriver /usr/local/bin/

ENTRYPOINT tail -f /dev/null
